# Generated by Django 5.0.6 on 2024-06-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_comments_counter_comment_post_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
    ]
