# Generated by Django 5.0.6 on 2024-06-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_postattachment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='post.postattachment'),
        ),
    ]
