# Generated by Django 5.0.6 on 2024-06-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends_number',
            field=models.IntegerField(default=0),
        ),
    ]
