# Generated by Django 5.0.6 on 2024-06-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_friends_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts_number',
            field=models.IntegerField(default=0),
        ),
    ]
